name: CVC5 Manager

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Optional: Commit hash to add to build queue'
        required: false
        type: string
  schedule:
    - cron: '*/15 * * * *'

jobs:
  manager:
    uses: ./.github/workflows/manager.yml
    with:
      solver: cvc5
      commit_hash: ${{ inputs.commit_hash || '' }}
    secrets: inherit
