name: Build CVC5

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Optional: CVC5 commit hash to add to build queue'
        required: false
        type: string
  schedule:
    - cron: '5,35 * * * *'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      solver: cvc5
      commit_hash: ${{ inputs.commit_hash || '' }}
    secrets: inherit
