name: Z3 Coverage Daily Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/coverage-daily-check.yml
    with:
      solver: z3
    secrets: inherit
